title: Test-Time Distribution Normalization For Contrastively Learned Vision-language Models
description: "A NeurIPS 2023 Paper by"
buttons:
  Paper: "https://arxiv.org/abs/2302.11084"
  Code: "https://github.com/fengyuli-dev/distribution-normalization"
  Slides: "./assets/slides.pdf"
theme: jekyll-theme-cayman

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
