title: "Distribution Normalization: An “Effortless” Test-Time Augmentation for Contrastively Learned Visual-language Models"
description: "A NeurIPS 2023 Paper by"
buttons:
  arXiv: 'https://arxiv.org/abs/2302.11084'
  Code: "https://github.com/fengyuli-dev/distribution-normalization"
  Poster: "/pending"
  Video: "/pending"
  Slides: "/pending"
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme